Repository FidelCly/dashboard, pull requests merged in 2023-08, with the labels that each got.

#1076 Fix: login redirection
  src/pages/auth/signin.tsx
Labels: enhancement

#1088 fix: build
  src/Components/html/Navbar.tsx
  src/pages/api/promotions/[id].ts
  src/pages/api/promotions/index.ts
  src/pages/api/shop/[id]/promotion.ts
  src/pages/campagne/index.tsx
  src/pages/scanner/index.tsx
  src/pages/settings/index.tsx
  src/test/Components/form/PromotionCreateForm.cy.tsx
Labels: bug

#1091 fix: form
  src/Components/List/CampaignList.tsx
  src/Components/List/PromotionList.tsx
  src/Components/List/ShopList.tsx
  src/Components/form/Shop.form.tsx
Labels: bug

#1145 feat : add delete promotion
  src/Components/List/PromotionList.tsx
Labels: enhancement

#1144 fix: profile route
  src/Components/auth/Profile.tsx
  src/pages/me/index.tsx
  src/pages/promotion/index.tsx
Labels: bug

#1142 feat: add checkout message
  src/Components/scanner.tsx
Labels: enhancement

#1146 fix: form validation errors
  src/Components/form/Campaign.form.tsx
  src/Components/form/Promotion.form.tsx
  src/Components/form/Shop.form.tsx
  src/pages/auth/signin.tsx
  src/pages/auth/signup.tsx
Labels: bug, enhancement

#1137 Feat/rework settings pages
  package.json
  pnpm-lock.yaml
  src/Components/form/Promotion.form.tsx
  src/Components/form/Shop.form.tsx
  src/Components/form/User.form.tsx
  src/Components/html/Navbar.tsx
  src/Components/html/Sidebar.tsx
  src/Models/Promotions.ts
  src/Models/User.ts
  src/pages/api/auth/[id]/update.ts
  src/pages/api/user/[uuid]/index.ts
  src/pages/settings/index.tsx
Labels: enhancement

#1204 feat: add animations and refactor css
  src/components/form/Campaign.form.tsx
  src/components/form/Promotion.form.tsx
  src/components/form/Shop.form.tsx
  src/components/form/User.form.tsx
  src/components/layout/Navbar.tsx
  src/components/list/CampaignList.tsx
  src/components/list/CardsList.tsx
  src/components/list/PromotionList.tsx
  src/components/scanner.tsx
  src/pages/index.tsx
Labels: enhancement

#1205 feat: use states for lists management
  src/components/form/Campaign.form.tsx
  src/components/form/Promotion.form.tsx
  src/components/list/CampaignList.tsx
  src/components/list/PromotionList.tsx
  src/models/Campaign.ts
  src/models/Promotions.ts
  src/pages/auth/signin.tsx
  src/pages/campaign/index.tsx
  src/pages/promotion/index.tsx
  src/test/Components/form/PromotionCreateForm.cy.tsx
  src/test/Components/list/PromotionList.cy.tsx
Labels: enhancement
